### ISSUE TITLE
How to create credentials of the liquidator/rollover/arbitrage wallets

### ISSUE THREAD

**Issue by timogoosen** [DistributedCollective/Sovryn-Node#112]
I'm trying to create a docker-compose and Dockerfile for this project (that I plan to use in another project that I saw on a hackathon on gitcoin.)

I can't seem to figure out how to do step 5 in the README.md:

```

Create directory "secrets" and within a file accounts.js with the credentials of the liquidator/rollover/arbitrage wallets
Readme mentions this step?
```

Could someone point me in the right direction please?

**Comment by koirikivi** [comment]
This part is perhaps a bit poorly documented.

The `ks` part referred to in readme is a password-encrypted keystore created with `web3.eth.accounts.encrypt`. It looks something like this:

```
{
    "version": 3,
    "id": "11111111-2222-3333-4444-555555555555",
    "address": "0x1234567890123456789012345678901234567890",
    "crypto": {
        "ciphertext": "1111111111111111111111111111111111111111111111111111111111111111",
        "cipherparams": {
            "iv": "22222222222222222222222222222222"
        },
        "cipher": "aes-128-ctr",
        "kdf": "scrypt",
        "kdfparams": {
            "dklen": 11,
            "salt": "1111111111111111111111111111111111111111111111111111111111111111",
            "n": 1111,
            "r": 1,
            "p": 1
        },
        "mac": "1111111111111111111111111111111111111111111111111111111111111111"
    }
}
```

However, instead of using it, you can just specify the private keys directly (which is of course less secure, since your private keys are stored in plaintext in the config):

```
export default {
    "liquidator": [{
        adr: "0x1234567890123456789012345678901234567890",
        pKey: "1234567890123456789012345678901234567890123456789012345678901234"
    }],
    "rollover": [{
        adr: "0x1234567890123456789012345678901234567891",
        pKey: "1234567890123456789012345678901234567890123456789012345678901234"
    }],
    "arbitrage": [{
        adr: "0x1234567890123456789012345678901234567892",
        pKey: "1234567890123456789012345678901234567890123456789012345678901234"
    }],
}
```

After doing this, there's an (undocumented) utility for creating `accounts.js` with encrypted keystores. It can be run with:

```
node -r esm util/encryptAccounts.js
```

Note that if you use the keystores instead of unencrypted private keys, you have to specify the keystore password as an argument when running the program, eg:

```
npm run start:test -- MySecretKeystorePassword
```

**Comment by timogoosen** [comment]
Thanks @koirikivi
